# Generated by Django 4.2.10 on 2024-02-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                ("image", models.ImageField(upload_to="images/products")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "AVAILABLE"),
                            ("out_of_stock", "OUT_OF_STOCK"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
