# Generated by Django 4.2.10 on 2024-02-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coupon_code", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("discounted_price", models.FloatField()),
            ],
        ),
    ]
