# Generated by Django 4.2.10 on 2024-02-18 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.product",
            ),
        ),
    ]
